import json
from pathlib import Path
from config import RELEVANCE_DIR, CLASSIFICATION_DIR, SUMMARY_DIR, COMPARISON_DIR, REPORT_DIR, BASE_DIR
from file_utils import load_json, save_text
from ollama_utils import chat_with_ollama

SYSTEM_PROMPT = """
You are an Expert Multi-Domain Research Report Generator.

Your task is to generate a deep, high-quality, and structured research report based on provided research data and papers.

The report must follow the visual aesthetic of professional scientific summaries, using emojis for clarity and structured tables for comparison.

-----------------------------------
🎯 OBJECTIVE
Generate a detailed research report that:
- Answers the user query clearly and authoritatively.
- Adapts terminology and context based on the domain (AI, Finance, Med, etc.).
- Uses visual indicators (emojis, ratings) for quick insights.
- Provides a "Final Answer" that includes a Use Case mapping.

-----------------------------------
📝 REPORT STRUCTURE (MANDATORY 14 SECTIONS)

1. 📄 TITLE PAGE: 🧾 Title, User Query, "Generated by Multi-Agent Research System", Date.
2. 📌 ABSTRACT: (150–200 words) Summarize problem, methods, key findings, and final conclusion.
3. 📖 INTRODUCTION: Write a domain-aware intro. Adapt terminology: AI -> compute, Finance -> risk, Med -> clinical challenges.
4. 🎯 PROBLEM STATEMENT: Define query and constraints (Low GPU, Limited Data, etc.).
5. ⚙️ METHODOLOGY: Explain the multi-agent pipeline (Query Opt, Retrieval, Scoring, Analysis) generically.
6. 📊 SELECTED PAPERS OVERVIEW: Markdown table (Paper | Approach | Key Idea | Efficiency).
7. 🔍 PER-PAPER ANALYSIS: For EACH paper: Problem, Approach, Key Idea, Results, Efficiency, Limitations.
8. 📊 CROSS-PAPER COMPARISON: Markdown table (Approach | Resource Usage | Data Needs | Accuracy | Efficiency Rating ⭐).
9. 🧠 ARCHITECTURE ANALYSIS: Categorize approaches using:
   - 🟢 Low Resource / High Efficiency
   - 🟡 Balanced / Moderate Usage
   - 🔴 High Resource Usage
10. 🏆 FINAL ANSWER (CRITICAL):
    - 🏆 Use Case Mapping Table (Use Case | Best Architecture).
    - ✅ Overall Best Recommendation (Best approach, Why, Alternatives).
11. 🔑 KEY FINDINGS: Bullet points of major insights and patterns.
12. ⚠️ RESEARCH GAPS: Missing info or research limitations.
13. 🔮 FUTURE WORK: Improvements and research directions.
14. 📌 FINAL CONCLUSION: Clear summary and final takeaway.

-----------------------------------
📌 IMPORTANT RULES
- Use emojis in section headers as shown above.
- Adapt terminology dynamically: AI -> model/architecture, Finance -> risk/strategy, Engineering -> system.
- Always justify conclusions using evidence from the provided paper snippets.
- Use star ratings (⭐⭐⭐⭐⭐) in the comparison tables.
- Return clean, professional, and structured markdown.
"""

def load_all_context():
    # Base output dirs
    query_output_dir = Path("query_output")
    
    def safe_load(path, default=None):
        if Path(path).exists():
            return load_json(path)
        return default if default is not None else []

    reasoning_dir = BASE_DIR / "research_outputs" / "reasoning"

    context = {
        "relevance": safe_load(RELEVANCE_DIR / "all_relevance_ranked.json", []),
        "classifications": safe_load(CLASSIFICATION_DIR / "all_classifications.json", []),
        "summaries": safe_load(SUMMARY_DIR / "all_summaries.json", []),
        "comparison": safe_load(COMPARISON_DIR / "cross_paper_comparison.json", {}),
        "query_data": safe_load(query_output_dir / "query_data.json", {}),
        "runtime_config": safe_load(query_output_dir / "runtime_config.json", {}),
        "reasoning": safe_load(reasoning_dir / "final_reasoning.json", {})
    }
    
    # Metadata for references
    metadata_file = Path("downloaded_papers/related_papers_metadata.json")
    context["metadata"] = safe_load(metadata_file, [])
        
    # Load parsed JSON files for full text snippets
    parsed_dir = BASE_DIR / "research_outputs" / "parsed_json"
    parsed_papers = []
    if parsed_dir.exists():
        for file in parsed_dir.glob("*.json"):
            parsed_papers.append(load_json(file))
    context["parsed_papers"] = parsed_papers

    return context

def format_papers_for_report(ctx):
    """Format papers into the Title/Abstract/Key insights structure for the LLM."""
    formatted = []
    # Use relevance ranked papers to maintain order
    relevance_list = ctx.get("relevance", [])
    summaries = {s.get("paper_id"): s for s in ctx.get("summaries", [])}
    classifications = {c.get("paper_id"): c for c in ctx.get("classifications", [])}
    metadata = {m.get("paper_id"): m for m in ctx.get("metadata", [])}
    parsed = {p.get("paper_id"): p for p in ctx.get("parsed_papers", [])}

    for item in relevance_list[:8]:  # Top 8 papers for depth
        pid = item.get("paper_id")
        m = metadata.get(pid, {})
        s = summaries.get(pid, {})
        c = classifications.get(pid, {})
        p = parsed.get(pid, {})
        
        # Take first 3000 chars of actual paper text to ground LLM hallucination
        raw_text_snippet = p.get("full_text", "")[:3000]

        paper_info = f"""
PAPER TITLE: {m.get('title', item.get('title', 'Unknown Title'))}
ABSTRACT: {m.get('abstract', 'No abstract available.')}
KEY INSIGHTS:
- Problem: {s.get('problem', 'N/A')}
- Core Idea: {s.get('core_idea', 'N/A')}
- Methodology: {s.get('method', 'N/A')}
- Results/Metrics: {s.get('results', 'N/A')}
- Limitations: {s.get('limitations', 'N/A')}
- Relevance: {s.get('why_relevant_to_query', 'N/A')}

PAPER CONTENT SNIPPET:
{raw_text_snippet}
"""
        formatted.append(paper_info.strip())
    
    return "\n\n---\n\n".join(formatted)

def run_final_report(query_str=None):
    ctx = load_all_context()
    query = query_str or ctx["runtime_config"].get("query", "Unknown Query")
    
    formatted_papers = format_papers_for_report(ctx)
    
    # Format reasoning engine conclusions for the report
    reasoning = ctx.get("reasoning", {})
    reasoning_block = ""
    if reasoning and not reasoning.get("error"):
        reasoning_block = f"""

EXPERT REASONING ENGINE CONCLUSIONS (USE THIS FOR FINAL ANSWER):
- Query Target Type: {reasoning.get('query_target', 'N/A')}
- Constraints: {json.dumps(reasoning.get('constraints', []))}
- Best Overall Answer: {reasoning.get('best_overall_answer', 'N/A')}
- Best By Scenario: {json.dumps(reasoning.get('best_by_scenario', []), indent=2)}
- Reasoning Summary: {reasoning.get('reasoning_summary', 'N/A')}
- Confidence: {reasoning.get('confidence', 'N/A')}
- Warning: {reasoning.get('warning', 'None')}
"""

    user_prompt = f"""
USER QUERY: {query}

SELECTED PAPERS DATA:
{formatted_papers}

ADDITIONAL PIPELINE CONTEXT:
- Search Strategy: {json.dumps(ctx['query_data'].get('optimized_queries', []), indent=2)}
- Core Keywords: {json.dumps(ctx['query_data'].get('core_keywords', []), indent=2)}
- Comparison Matrix Data: {json.dumps(ctx['comparison'], indent=2)}
{reasoning_block}
IMPORTANT: For Section 10 (Final Answer), you MUST use the Expert Reasoning Engine Conclusions above.
Do NOT answer with hardware (CPU/GPU) if the query asks for a model/architecture.

Please generate the Expert Multi-Domain Research Report following the 14-step structure exactly.
"""

    report = chat_with_ollama(SYSTEM_PROMPT, user_prompt)
    
    # Ensure final output directory exists
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    save_text(REPORT_DIR / "final_research_report.md", report)

    print("\n✅ Final scientific report created.")
    print(f"📍 Saved at: {REPORT_DIR / 'final_research_report.md'}")
    return report

if __name__ == "__main__":
    try:
        from runtime_config import load_runtime_config
        runtime = load_runtime_config()
        query = str(runtime.get("query", "")).strip()
    except Exception:
        query = None

    run_final_report(query)
